//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation

extension AppResolver {

    func resolveAPIClient() -> APIClient {
        return provideAPIClient()
    }

    func resolveAppResolver() -> AppResolver {
        return provideAppResolver()
    }

}

