//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import UIKit

extension AppResolver {

    func resolveAPIClient() -> APIClient {
        return provideAPIClient()
    }

    func resolveAppResolver() -> AppResolver {
        return provideAppResolver()
    }

    func resolveRepositoriesViewController() -> RepositoriesViewController {
        let appResolver = resolveAppResolver()
        return RepositoriesViewController.makeInstance(dependency: .init(appResolver: appResolver))
    }

}

